name: boris-300116973

on: [push]

jobs:
  mon-script:
    name: Le script CI-CD de boris
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          git pull
          cd 6.CI-CD
          bash 300116973/programme.sh
          with:
          MON_NOM: "Mona"
          
      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m :cake::apple:
          git push
